Failed to execute action: test_server()
Traceback (most recent call last):
  File "/home/limyreth/pyautomate/pyautomate/main.py", line 104, in <module>
    eval(action, vars(config))
  File "<string>", line 1, in <module>
  File "/home/limyreth/.texttest/tmp/dynamic_gui.19Jun225659.4193/tt/stop_at_first_failed_action/auto.py", line 25, in test_server
    print(this_will_stop_execution)
NameError: global name 'this_will_stop_execution' is not defined
