Failed to execute action: test_server()
Traceback (most recent call last):
  File "/home/limyreth/pyautomate/pyautomate/main.py", line 19, in <module>
    application.run()
  File "/home/limyreth/pyautomate/pyautomate/application.py", line 28, in run
    self.execute_path(config, dfa, options.exact)
  File "/home/limyreth/pyautomate/pyautomate/application.py", line 137, in execute_path
    eval(action, vars(config))
  File "<string>", line 1, in <module>
  File "/home/limyreth/.texttest/tmp/tt.25Jun231445.12773/tt/stop_at_first_failed_action/auto.py", line 34, in test_server
    print(this_will_stop_execution)
NameError: global name 'this_will_stop_execution' is not defined
