Failed to execute action: start_server()
Traceback (most recent call last):
  File "/home/limyreth/pyautomate/pyautomate/main.py", line 133, in <module>
    execute_path(dfa, options.exact)
  File "/home/limyreth/pyautomate/pyautomate/main.py", line 113, in execute_path
    eval(action, vars(config))
  File "<string>", line 1, in <module>
NameError: name 'start_server' is not defined
